### ISSUE TITLE
Receive also static address

### ISSUE THREAD

**Issue by arturszigurs** [arturszigurs/turbulent-quack#3]
Not only dynamic adresses should be received but static ones as well in format 192.168.1.xxx.
xxx varies in range of 2..254.

**Comment by janiszigurs** [comment]
Should I try to get all static IP addresses(ping all : 192.168.1.xxx) or the only ones in ARP table?

**Comment by arturszigurs** [comment]
Pinging should go only to adresses that are in ARP table otherwise it would take too much time to ping all of them. (255)

**Comment by arturszigurs** [comment]
Marking this as complete as this has already been implemented
